name: Browser Automation Tests
on: 
  workflow_dispatch
jobs:
  print_inputs:
    runs-on: [self-hosted]
    steps:
    - name: Print context
      run: |
        echo "Payload: ${{ github.event.inputs.issueId }}"


    - run: |
        echo "Log level: ${{ github.event.inputs.logLevel }}"
        echo "Tags: ${{ github.event.inputs.tags }}" 


